### ISSUE TITLE
Code reviews

### ISSUE THREAD

**Issue by josefinco** [gewbittencourt/Tibia.Ciclopedia.WebAPI#2]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Application/UseCases/CreateItem/CreateItem.cs#L32

Aqui faz sentido retornar o ID do item como output

Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Application/UseCases/DeleteItem/DeleteItem.cs#L22

Se você não encontrar o item ao buscar pelo id, irá retornar erro ao tentar deletar, tratar validação


Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Application/UseCases/UpdateItem/UpdateAll/UpdateAllItem.cs#L13

Esse usecase poderia chamar apenas UpdateItem pois ele faz a atualização de todos as propriedade do item, da forma com que o nome foi utilizado da a sensação de estarmos atualizando todos os items

Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Application/UseCases/UpdateItem/UpdateAll/UpdateAllItem.cs#L29

Faz sentidor ter dois métodos apartados para atualizar o objeto? poderia atualizar a propriedade price no UpdateAllItem


Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Application/UseCases/UpdateItem/UpdateAll/UpdateAllItemCommand.cs#L12

Essa classe é necessária? já existe uma classe de Input para o usecase

Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Application/UseCases/UpdateItem/UpdatePrice/UpdateItemPrice.cs#L24

Necessário tratar caso o item não for encontrado na base de dados, dessa forma caso não for encontrado ocorrerá uma exception de null reference

Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Application/UseCases/UpdateItem/UpdatePrice/UpdateItemPriceCommand.cs#L17

Faz sentido essa classe já que está sendo utilizado uma classe de input?


Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Application/ApplicationModule.cs#L19

Sugestão: Você pode criar uma pasta chamada Extensions e mover a classe para lá, chamando de ApplicationExtensions e manter esse método lá, de qualquer forma, ficou muito bom a segregação de responsábilidades 


Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Domain/Entities/Item.cs#L26

Essa propriedade pode ser chamada de CreatedAt

Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Domain/Entities/Item.cs#L47

Esse método pode estar dentro de uma classe static chamada Mapper, ela recebe um objeto CreateItemInput e faz o mapeamento para um novo objeto item já inserindo os valores


necessário sendo que estou usando o automapper? Se sim, não sei como fazer.

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/tree/master/Tibia.Ciclopedia.Domain/Entities

Essa pasta pode ser chamada de Items e com isso organizamos melhor o domínio da aplicação


Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Domain/Interface/IItemRepository.cs#L5

Sugestão: Essa classe poderia estar contida dentro da pasta items, pois estamos falando de um repository de items

Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/tree/master/Tibia.Ciclopedia.Domain/ValueObjects

Faz sentido chamar essa Classe de ValueObjects?

_"Value objects encapsulate a set of primitive values and related invariants. A few examples of value objects are money and date range objects"_
https://www.milanjovanovic.tech/blog/value-objects-in-dotnet-ddd-fundamentals


Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Domain/ValueObjects/SlotsInfo.cs#L11

https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Domain/ValueObjects/SlotsInfo.cs#L12

Propriedade de domínio DEVEM ter setters privados ou inexistentes


Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Infrastructure.MongoDb/Collection/ItemCollection.cs#L13

Faz sentido adicionar a anotação [BsonIgnoreExtraElements]?

Não localizei.

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Infrastructure.MongoDb/Collection/ItemCollection.cs#L32

Faz sentido essa propriedade ser uma string já que existe um enum de Vocations?

Done. Alterado também para ItemType

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Infrastructure.MongoDb/Repository/ItemRepository.cs#L61

Faz sentido uma especialização de método update? Podemos utilizar somente um método chamado update que lida com a atualização do objeto na base


Done.

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.Infrastructure.MongoDb/Repository/ItemRepository.cs#L74

Alterar o nome do método, conforme descrito no usecase

Done

**Comment by josefinco** [comment]
https://github.com/gewbittencourt/Tibia.Ciclopedia.WebAPI/blob/8f3281ed50a88a56605ad3e391ac7c6f8429365b/Tibia.Ciclopedia.API/Controllers/ItemController.cs#L54

Sugestão: 

		[HttpPut]
		[Route("Price/{itemId}")]
		public async Task<IActionResult> UpdatePrice([FromRoute] Guid id ,[FromBody] UpdateItemPriceInput request)
		{
			request.setId(itemId)
			var result = await _mediator.Send(new UpdateItemPriceCommand(id, request));
			return Ok(result);
		}
		
		Done

**Comment by josefinco** [comment]
Adicionar dentro da collection Items um index no mongo para o name. Efetuar a inclusão do index via código no momento do startup da aplicação

Done?

**Comment by gewbittencourt** [comment]
Problemas corrigidos.
